// Currency profiles — original editorial content about each currency used on pair pages.
// Kept intentionally specific and non-templated to avoid thin-content flags.

export const CURRENCY_PROFILES = {
  USD: {
    country: 'United States',
    centralBank: 'Federal Reserve System',
    subunit: '1 dollar = 100 cents',
    rank: 'world reserve currency',
    about: 'The US dollar is the most traded currency on Earth, appearing on one side of roughly 88% of all foreign-exchange trades. It anchors global trade in commodities like oil and gold, and makes up more than 58% of official foreign-exchange reserves. When investors seek safety during global uncertainty, they typically move into dollars — a pattern known as a "flight to quality".',
    usage: 'Beyond the United States, the dollar is legal tender or a widely accepted parallel currency in countries such as Ecuador, El Salvador, Panama, Zimbabwe, and several Caribbean nations. Many emerging-market economies quote property, luxury goods, and international contracts directly in USD.',
  },
  EUR: {
    country: 'European Union (20 eurozone members)',
    centralBank: 'European Central Bank (ECB)',
    subunit: '1 euro = 100 cents',
    rank: '2nd most-traded currency',
    about: 'Introduced in 1999 for accounting and 2002 as physical cash, the euro is the single currency shared by 20 European Union member states. It is the second largest reserve currency after the dollar, making up about 20% of global foreign-exchange reserves. The EUR/USD pair is the single most actively traded currency pair in the world.',
    usage: 'Inside the eurozone, the euro eliminates conversion costs between member states. Non-euro EU countries such as Denmark, Sweden, Poland, and Czechia still use their own currencies, so travelers should check before assuming "Europe" means euros.',
  },
  GBP: {
    country: 'United Kingdom',
    centralBank: 'Bank of England',
    subunit: '1 pound = 100 pence',
    rank: '4th most-traded currency',
    about: 'The pound sterling is the oldest currency still in continuous use, with roots reaching back more than 1,200 years. Historically stronger than most major currencies on a per-unit basis, GBP is also one of the most politically sensitive — Brexit and UK fiscal events have triggered some of its largest single-day movements in modern history.',
    usage: 'The pound is also used in British Crown Dependencies (Jersey, Guernsey, Isle of Man) and British Overseas Territories, though these issue their own local variants. In the Republic of Ireland, the currency is the euro, not the pound.',
  },
  JPY: {
    country: 'Japan',
    centralBank: 'Bank of Japan (BoJ)',
    subunit: 'Effectively no subunit in everyday use (the sen was phased out in 1954)',
    rank: '3rd most-traded currency',
    about: 'The yen is distinctive among majors for its very low unit value — prices in Japan are quoted in whole yen, with no smaller division in daily use. For decades the BoJ has run an ultra-loose monetary policy to combat deflation, making the yen a popular "funding currency" for carry trades. JPY also acts as a safe haven: it tends to strengthen sharply when global risk appetite falls.',
    usage: 'Japan is the only country that issues the yen. It is one of the most cash-intensive major economies, so travelers should expect to carry more physical yen than they would dollars or euros elsewhere.',
  },
  CHF: {
    country: 'Switzerland (and Liechtenstein)',
    centralBank: 'Swiss National Bank (SNB)',
    subunit: '1 franc = 100 rappen (or centimes)',
    rank: '6th most-traded currency',
    about: 'The Swiss franc is widely considered the ultimate safe-haven currency. Swiss political neutrality, strong property rights, large foreign reserves, and a deeply trusted banking system mean CHF tends to appreciate in times of global stress. The SNB has periodically intervened in markets to cap that appreciation — most famously removing a EUR/CHF floor in January 2015 in a move that shocked global FX markets.',
    usage: 'CHF is also used in Liechtenstein and, informally, in some nearby border regions. Switzerland is not part of the EU or the eurozone and shows no signs of adopting the euro.',
  },
  CAD: {
    country: 'Canada',
    centralBank: 'Bank of Canada',
    subunit: '1 dollar = 100 cents',
    rank: '5th most-traded currency',
    about: 'Nicknamed the "loonie" after the bird pictured on the C$1 coin, the Canadian dollar is heavily correlated with commodity prices — particularly crude oil, which is Canada\'s largest export. The USD/CAD pair is one of the most stable of the majors because the US and Canadian economies are deeply integrated and move together.',
    usage: 'CAD is only legal tender in Canada, though some US border towns informally accept it at a discount.',
  },
  AUD: {
    country: 'Australia',
    centralBank: 'Reserve Bank of Australia (RBA)',
    subunit: '1 dollar = 100 cents',
    rank: '6th most-traded currency',
    about: 'The Australian dollar is a classic "risk-on" currency: it tends to rise when global investors are optimistic and fall in risk-off periods. It is also highly sensitive to commodity prices (iron ore, coal, LNG) and to Chinese economic activity, given how much of Australia\'s export volume flows to China.',
    usage: 'AUD is also legal tender in several Pacific nations — Kiribati, Nauru, Tuvalu — and is widely accepted in some others.',
  },
  NZD: {
    country: 'New Zealand',
    centralBank: 'Reserve Bank of New Zealand (RBNZ)',
    subunit: '1 dollar = 100 cents',
    rank: '10th most-traded currency',
    about: 'The "kiwi" behaves similarly to the Australian dollar but with greater volatility and a smaller economic base. Historically the RBNZ was the first central bank in the world to adopt an explicit inflation target, in 1990 — a practice since copied globally.',
    usage: 'NZD is also used in several small Pacific territories including the Cook Islands, Niue, Pitcairn Islands, and Tokelau.',
  },
  BRL: {
    country: 'Brazil',
    centralBank: 'Banco Central do Brasil',
    subunit: '1 real = 100 centavos',
    rank: 'Largest Latin American currency',
    about: 'The Brazilian real was introduced in 1994 as part of the Plano Real, which ended decades of hyperinflation. It is a commodity-linked currency, heavily influenced by prices of iron ore, soy, and beef — Brazil\'s largest exports. BRL is one of the most volatile emerging-market currencies, reacting strongly to both domestic politics and global risk sentiment.',
    usage: 'BRL is only used in Brazil. Tourists should avoid exchanging at airports, where spreads are notoriously wide.',
  },
  MXN: {
    country: 'Mexico',
    centralBank: 'Banco de México',
    subunit: '1 peso = 100 centavos',
    rank: 'Most-traded emerging-market currency',
    about: 'The Mexican peso is the most actively traded emerging-market currency in the world, thanks to Mexico\'s deep trade relationship with the United States and its fully convertible currency regime. MXN tends to strengthen when US growth is strong and weaken with cross-border political tension.',
    usage: 'In towns along the US-Mexico border, prices are often quoted in both MXN and USD, with local shops accepting either.',
  },
  CNY: {
    country: 'China',
    centralBank: 'People\'s Bank of China (PBoC)',
    subunit: '1 yuan = 10 jiao = 100 fen',
    rank: '5th most-traded currency',
    about: 'The renminbi (official name) or yuan (unit) is managed by the PBoC within a tolerance band against a basket of trade partners. It is not fully freely floating, so its moves are quieter than comparable majors. An offshore variant, CNH, trades freely in Hong Kong and is often slightly different from the onshore CNY.',
    usage: 'Within mainland China, digital payment apps (WeChat Pay, Alipay) dominate — most vendors cannot make change for cash. Travelers should ensure at least one digital payment method works before arrival.',
  },
  INR: {
    country: 'India',
    centralBank: 'Reserve Bank of India (RBI)',
    subunit: '1 rupee = 100 paise',
    rank: 'Major regional currency',
    about: 'The Indian rupee is the official currency of the world\'s most populous country. Strict capital controls mean the INR does not trade as freely internationally as the majors, but its value still responds to Indian inflation, interest-rate policy, and global oil prices (India is a major oil importer).',
    usage: 'Outside India, travelers typically need to exchange on arrival. Digital payments (UPI) have expanded dramatically and many merchants prefer them to cash.',
  },
  KRW: {
    country: 'South Korea',
    centralBank: 'Bank of Korea',
    subunit: 'Effectively no subunit in everyday use',
    rank: 'Major Asian currency',
    about: 'The South Korean won is the currency of one of the world\'s most technology-driven economies. Like the yen, prices are typically quoted in whole won without a subunit. KRW is sensitive to global semiconductor cycles — Korea is home to some of the largest memory-chip and display makers in the world.',
    usage: 'Cash is still common in Korea, though contactless card and mobile payments are rapidly displacing it.',
  },
  SGD: {
    country: 'Singapore',
    centralBank: 'Monetary Authority of Singapore (MAS)',
    subunit: '1 dollar = 100 cents',
    rank: 'Major Asian financial-hub currency',
    about: 'The Singapore dollar is managed against an undisclosed basket of trading-partner currencies rather than a single peg, which gives it unusual stability. MAS adjusts its monetary policy through the exchange rate itself rather than primarily through interest rates — a rare approach among central banks.',
    usage: 'SGD is legal tender in Singapore and informally accepted alongside the Brunei dollar in Brunei under a long-standing agreement.',
  },
  HKD: {
    country: 'Hong Kong SAR',
    centralBank: 'Hong Kong Monetary Authority (HKMA)',
    subunit: '1 dollar = 100 cents',
    rank: 'Major Asian financial-hub currency',
    about: 'The Hong Kong dollar has been pegged to the US dollar since 1983, within a narrow trading band of roughly HK$7.75–7.85 per USD. This peg is maintained by HKMA market intervention and is one of the longest-running currency arrangements of its kind.',
    usage: 'Because of the peg, converting USD to HKD rarely changes noticeably from day to day — unusual behavior that makes HKD a predictable currency for travelers and cross-border business.',
  },
  NOK: {
    country: 'Norway',
    centralBank: 'Norges Bank',
    subunit: '1 krone = 100 øre',
    rank: 'Major European currency (non-euro)',
    about: 'The Norwegian krone is a petrocurrency: its value is strongly tied to the price of crude oil, which is the backbone of Norway\'s export economy and the source of the world\'s largest sovereign wealth fund. Norway is in the European Economic Area but not the EU, and has kept its own currency.',
    usage: 'Norway is one of the most cashless societies in the world — some shops and public services no longer accept cash at all.',
  },
  SEK: {
    country: 'Sweden',
    centralBank: 'Sveriges Riksbank',
    subunit: '1 krona = 100 öre',
    rank: 'Major European currency (non-euro)',
    about: 'Sweden is an EU member but has never adopted the euro, keeping the krona instead. The Riksbank is one of the oldest central banks in the world (founded 1668) and was among the first to experiment with negative interest rates.',
    usage: 'Like Norway, Sweden is largely cashless — contactless cards and the Swish mobile-payment app dominate everyday transactions.',
  },
  DKK: {
    country: 'Denmark',
    centralBank: 'Danmarks Nationalbank',
    subunit: '1 krone = 100 øre',
    rank: 'Major European currency (non-euro)',
    about: 'The Danish krone is pegged to the euro within a narrow band — a stability arrangement that means DKK moves almost one-for-one with EUR against every other currency. Denmark has opted out of the euro despite satisfying the technical conditions to join.',
    usage: 'Greenland and the Faroe Islands, both part of the Kingdom of Denmark, use the Danish krone as well.',
  },
  AED: {
    country: 'United Arab Emirates',
    centralBank: 'Central Bank of the UAE',
    subunit: '1 dirham = 100 fils',
    rank: 'Major Gulf currency',
    about: 'The UAE dirham has been pegged to the US dollar at approximately 3.6725 AED per USD since 1997. This peg underpins the Gulf state\'s role as a global trade, tourism, and finance hub. Like HKD, AED behaves predictably against USD but moves with USD against every other currency.',
    usage: 'AED is widely accepted across the seven emirates including Dubai and Abu Dhabi. Hotels and tourist businesses often quote prices in USD as well.',
  },
  SAR: {
    country: 'Saudi Arabia',
    centralBank: 'Saudi Central Bank (SAMA)',
    subunit: '1 riyal = 100 halalas',
    rank: 'Major Gulf currency',
    about: 'The Saudi riyal has been pegged to the US dollar at 3.75 SAR per USD since 1986 — a central piece of the "petrodollar" system, where oil is priced and settled in dollars. The stability of the riyal has been a deliberate policy choice aligned with Saudi Arabia\'s role as the world\'s largest oil exporter.',
    usage: 'SAR is only used in Saudi Arabia. Non-Muslim tourism has expanded significantly since 2019, and card payments are now widely accepted in major cities.',
  },
  ILS: {
    country: 'Israel',
    centralBank: 'Bank of Israel',
    subunit: '1 shekel = 100 agorot',
    rank: 'Major Middle Eastern currency',
    about: 'The new Israeli shekel replaced the old shekel in 1985 during a successful anti-inflation program. The shekel has become one of the more stable Middle Eastern currencies, supported by a strong technology export sector and frequently cited as a model for currency reform.',
    usage: 'ILS is the official currency of Israel and is also widely used in the Palestinian territories alongside the Jordanian dinar and US dollar.',
  },
}

export function getProfile(code) {
  return CURRENCY_PROFILES[code]
}
