// Editorial guides — original content, hand-written for currencyabout.com.
// Each guide is a structured article used to build the /guides section.

export const GUIDES = [
  {
    slug: 'how-exchange-rates-work',
    title: 'How Exchange Rates Work: A Plain-English Guide',
    description: 'Exchange rates shape the price of almost everything you buy from abroad. Here is how they are set, why they move, and what the numbers actually mean.',
    readingMinutes: 7,
    updated: '2026-04-20',
    category: 'Fundamentals',
    tags: ['basics', 'forex', 'education'],
    body: [
      { type: 'lead', text: 'An exchange rate is the price of one currency expressed in another. "1 USD = 5.02 BRL" means that, right now, one US dollar trades for 5.02 Brazilian reais. Simple on the surface — but the machinery behind that number touches every imported product, every online purchase in a foreign store, every trip abroad.' },
      { type: 'h2', text: 'Who sets the rate?' },
      { type: 'p', text: 'For most major currencies, no single entity "sets" the rate. Instead, it emerges from a global, always-on market where banks and financial institutions buy and sell currencies from each other. This interbank market is decentralized, open 24 hours on weekdays, and handles more than $7 trillion in daily volume, according to the Bank for International Settlements.' },
      { type: 'p', text: 'What you see quoted on sites like this one is the mid-market rate — the midpoint between the price at which banks are buying and selling. It is a reference point, not the rate you typically receive at the till.' },
      { type: 'h2', text: 'What moves a rate up or down?' },
      { type: 'p', text: 'Four big forces dominate day-to-day changes:' },
      { type: 'list', items: [
        'Interest rates. When a central bank raises rates, holding that currency becomes more attractive, and money flows in.',
        'Inflation. Currencies with high, persistent inflation tend to weaken against stable ones.',
        'Trade balances. Countries that export more than they import see foreign buyers constantly converting into their currency.',
        'Political and fiscal risk. Unexpected elections, debt defaults, or policy shifts can move rates several percent in a day.',
      ] },
      { type: 'h2', text: 'Mid-market vs. the rate you actually get' },
      { type: 'p', text: 'If you change currency at an airport kiosk, you might see a number 5%–12% worse than the mid-market. A credit card abroad typically adds 1%–3%. A modern remittance service may add 0.3%–1.5%. The difference is the provider\'s margin and fees — it is how they make money.' },
      { type: 'callout', text: 'Before a large conversion, compare the mid-market rate (shown here) against your provider\'s quote. If the gap is over 2%, you can probably do better.' },
      { type: 'h2', text: 'Why rates can differ between websites' },
      { type: 'p', text: 'You may see slightly different rates on different currency sites. Reasons include: different data sources, caching windows (many free tools refresh once or twice a day), rounding, and whether a site quotes mid-market vs. an indicative retail rate. A variance of 0.1%–0.5% between reputable reference sites is normal.' },
      { type: 'h2', text: 'A quick mental model' },
      { type: 'p', text: 'Think of a currency like a stock. Its price moves constantly based on supply, demand, and expectations about the issuing country. When the news says "the pound fell," it means traders collectively were willing to accept fewer dollars (or euros) per pound than the day before. That is it. Everything else — charts, analyst quotes, technical indicators — is commentary on that one movement.' },
      { type: 'h2', text: 'What this means for you' },
      { type: 'list', items: [
        'For small transactions (under $100), the exact rate barely matters. Convenience and fees dominate.',
        'For medium amounts ($100–$5,000), the rate matters — compare two or three providers.',
        'For large or recurring conversions, use a service that shows the mid-market rate and a transparent fee. Avoid any service that quotes a "rate" with no fee broken out.',
      ] },
      { type: 'p', text: 'Understanding the basics above protects you from the most common trap in foreign exchange: paying a hidden margin disguised as "zero fees". Now you know what to look for.' },
    ],
  },

  {
    slug: 'understanding-us-dollar',
    title: 'Understanding the US Dollar (USD): The World\'s Reserve Currency',
    description: 'The US dollar anchors more than 60% of global reserves and is on one side of nearly 90% of all foreign-exchange trades. Here is why.',
    readingMinutes: 8,
    updated: '2026-04-20',
    category: 'Currency Guides',
    tags: ['usd', 'dollar', 'reserve-currency'],
    body: [
      { type: 'lead', text: 'The US dollar (ISO code: USD, symbol: $) is the most important currency on the planet by almost any measure. It prices most commodities, settles most international trade, and sits in the reserves of virtually every central bank. This guide explains why — and what that means in practice when you convert money to or from USD.' },
      { type: 'h2', text: 'Basic facts' },
      { type: 'list', items: [
        'ISO code: USD',
        'Symbol: $ (sometimes US$ to distinguish from other dollar currencies)',
        'Subunit: 1 dollar = 100 cents',
        'Issuer: Federal Reserve (the "Fed") — the central bank of the United States',
        'First issued in current form: 1914 (Federal Reserve notes)',
      ] },
      { type: 'h2', text: 'Why the dollar dominates' },
      { type: 'p', text: 'Three overlapping reasons made USD the default global currency in the 20th century, and they keep it there today.' },
      { type: 'p', text: 'First, the Bretton Woods agreement (1944) pegged most major currencies to the dollar, which was itself pegged to gold. The gold peg ended in 1971, but the habit of quoting and settling international trade in dollars stuck.' },
      { type: 'p', text: 'Second, the United States has the deepest, most liquid financial markets in the world. When a Japanese insurer or a German pension fund needs a safe, liquid place to park reserves, US Treasury bonds are the natural home.' },
      { type: 'p', text: 'Third, oil and most other commodities are priced in dollars. A refinery in Korea buying crude from Saudi Arabia will almost always settle in USD. That creates constant global demand that no other currency rivals.' },
      { type: 'h2', text: 'What moves USD' },
      { type: 'p', text: 'When you watch USD against other currencies, the most common drivers are:' },
      { type: 'list', items: [
        'Federal Reserve interest-rate decisions (announced eight times a year).',
        'US inflation data (CPI, typically released mid-month).',
        'Non-farm payrolls (monthly jobs report, first Friday of each month).',
        'Safe-haven flows — during global crises, money often runs into the dollar, pushing it up.',
      ] },
      { type: 'h2', text: 'Converting to or from USD' },
      { type: 'p', text: 'Because USD is quoted against virtually every other currency, conversion costs are usually lower than for exotic pairs. If you are converting a major currency into dollars, you should expect a spread of 0.3%–1% from the mid-market rate at a competitive provider, and 1%–3% at a typical bank.' },
      { type: 'callout', text: 'Tip: if you are sending USD abroad, the recipient\'s bank often converts on arrival at its own — usually worse — rate. Ask whether you can send in the local currency instead.' },
      { type: 'h2', text: 'Currencies pegged or heavily linked to USD' },
      { type: 'p', text: 'Several currencies hold a formal or informal peg to USD, meaning their value only moves when the dollar does. Examples include the Hong Kong dollar (HKD), Saudi riyal (SAR), UAE dirham (AED), and Panamanian balboa. When you convert USD into one of these, the rate barely changes day to day.' },
      { type: 'h2', text: 'The future of dollar dominance' },
      { type: 'p', text: 'Some analysts argue that the euro, the Chinese yuan, or even a future digital-currency basket will eventually chip away at dollar hegemony. That may be true over decades. For practical purposes — travel, shopping, remittances, small business — USD will continue to be the most useful currency to know in the near term.' },
      { type: 'h2', text: 'Related pages' },
      { type: 'p', text: 'See live USD rates on our homepage, or jump to specific pairs: USD/EUR, USD/GBP, USD/JPY, USD/BRL, USD/CAD.' },
    ],
  },

  {
    slug: 'understanding-euro',
    title: 'Understanding the Euro (EUR): The Currency of 20 Nations',
    description: 'The euro is the second most-traded currency in the world and the official currency of 20 EU member states. Here is how it works and why it matters.',
    readingMinutes: 7,
    updated: '2026-04-20',
    category: 'Currency Guides',
    tags: ['eur', 'euro', 'europe'],
    body: [
      { type: 'lead', text: 'The euro (ISO code: EUR, symbol: €) is the second most-traded currency after the US dollar and the official currency of 20 European Union member states — collectively known as the eurozone. This guide covers what it is, who issues it, what moves it, and what to watch when converting to or from EUR.' },
      { type: 'h2', text: 'Basic facts' },
      { type: 'list', items: [
        'ISO code: EUR',
        'Symbol: €',
        'Subunit: 1 euro = 100 cents',
        'Issuer: European Central Bank (ECB), based in Frankfurt',
        'Launched: 1 January 1999 (electronic), 1 January 2002 (coins and notes)',
        'Used by: Austria, Belgium, Croatia, Cyprus, Estonia, Finland, France, Germany, Greece, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, Netherlands, Portugal, Slovakia, Slovenia, Spain',
      ] },
      { type: 'h2', text: 'A single currency, 20 economies' },
      { type: 'p', text: 'The euro is unusual: a single currency shared by independent countries with very different economies. The ECB sets one interest rate that has to work for Germany and Greece, for France and Finland. This creates a tension that shapes much of euro-area politics and drives some of the euro\'s bigger movements against the dollar.' },
      { type: 'p', text: 'Countries that use the euro gave up control of their own monetary policy when they joined the eurozone. They can no longer devalue their currency independently — which makes their economies more integrated, but also more constrained in a crisis.' },
      { type: 'h2', text: 'What moves the euro' },
      { type: 'list', items: [
        'ECB interest-rate decisions (governing council meets eight times a year).',
        'Eurozone inflation data (flash estimate usually at month-end).',
        'Political events — elections in France, Germany, or Italy can all move EUR.',
        'Relative US-vs-eurozone economic strength. When the US grows faster than the eurozone, EUR/USD tends to fall.',
      ] },
      { type: 'h2', text: 'Converting to or from EUR' },
      { type: 'p', text: 'EUR is the second most liquid currency in the world, so spreads are typically narrow. You should expect under 1% at a competitive provider for any EUR-to-major conversion. Card transactions abroad in EUR often show a "dynamic currency conversion" option — always decline it and let your card issuer convert at their rate, which is usually much better.' },
      { type: 'callout', text: 'Inside the eurozone, there is no conversion between, say, French and Spanish prices — they are both in euros. That is the whole point of the single currency.' },
      { type: 'h2', text: 'EUR and non-eurozone EU countries' },
      { type: 'p', text: 'Not every EU country uses the euro. Denmark and Sweden have opted out. Bulgaria, Czech Republic, Hungary, Poland, and Romania plan to join eventually but keep their own currencies for now. When you travel to Prague (Czech Republic), you will need koruna, not euros — although many tourist-heavy shops accept euros at an unfavorable rate.' },
      { type: 'h2', text: 'The euro in global reserves' },
      { type: 'p', text: 'About 20% of global foreign-exchange reserves are held in euros, second only to USD. That makes EUR a key anchor currency for any country with meaningful trade with Europe — which is most of the world.' },
    ],
  },

  {
    slug: 'sending-money-abroad',
    title: 'How to Send Money Abroad: A Practical Guide for 2026',
    description: 'Banks, remittance services, fintech apps, cards — the options have never been wider or the price differences larger. Here is how to choose.',
    readingMinutes: 9,
    updated: '2026-04-20',
    category: 'How-to',
    tags: ['remittance', 'transfer', 'fees'],
    body: [
      { type: 'lead', text: 'Sending money across borders used to be slow, expensive, and opaque. It is still often expensive if you use the wrong tool — but the right tool can now move money in minutes at a cost close to the mid-market rate. This guide walks through the main options and how to compare them honestly.' },
      { type: 'h2', text: 'The true cost of an international transfer' },
      { type: 'p', text: 'Every international transfer has two costs: an explicit fee (shown to you) and an FX margin (hidden in the rate). A "zero fee" transfer with a 4% margin is worse than a transfer with a $5 fee and a 0.5% margin on most amounts.' },
      { type: 'p', text: 'To compare apples to apples, always look at: "How many units of the destination currency will land, total?" That single number cuts through the marketing.' },
      { type: 'h2', text: 'Option 1: Your bank' },
      { type: 'p', text: 'Using your bank\'s international wire transfer is the default for many people, and usually the most expensive choice. Expect fees of $15–$50 and FX margins of 2%–4%. Some banks also charge an intermediary-bank fee that gets deducted from the amount the recipient sees. For amounts under a few thousand dollars, banks almost always lose on price.' },
      { type: 'p', text: 'Banks are still worth using when: the recipient is also a customer of the same bank, the amount is very large and you need compliance paperwork, or regulatory requirements in one of the countries limit your options.' },
      { type: 'h2', text: 'Option 2: Remittance specialists' },
      { type: 'p', text: 'Services like Wise, Remitly, WorldRemit, OFX, and XE built their business on offering better rates than banks. Costs typically run 0.3%–1.5% all-in for major corridors, and transfers often arrive the same day.' },
      { type: 'p', text: 'Read the rate they show carefully — most specialists are transparent, but a few quote an inflated rate and hide the margin. Use the "how much will arrive" test.' },
      { type: 'h2', text: 'Option 3: Card payments' },
      { type: 'p', text: 'Paying with a credit or debit card in a foreign currency is not technically a "transfer," but it is the most common cross-border payment. Standard card networks (Visa, Mastercard) charge a network fee of about 0.2%–1% and your issuer usually adds 1%–3% on top. Travel-focused cards often reimburse or waive the issuer portion.' },
      { type: 'callout', text: 'If a foreign terminal asks whether to charge you in your home currency or the local currency, always choose the local currency. The "home currency" option uses a markup that is almost always worse than your card\'s own rate.' },
      { type: 'h2', text: 'Option 4: Peer-to-peer and crypto' },
      { type: 'p', text: 'For some corridors — particularly ones with strict capital controls or limited traditional infrastructure — people use peer-to-peer platforms or stablecoins. These can be cheap but carry counterparty, regulatory, and tax risk. They are not recommended unless you know what you are doing and understand the tax treatment in your country.' },
      { type: 'h2', text: 'How to choose' },
      { type: 'list', items: [
        'Under $500: pick whatever is fastest and most convenient. Cost differences are small in absolute terms.',
        '$500–$10,000: spend five minutes comparing 2–3 remittance specialists. You will typically save 1%–3% over a bank.',
        'Over $10,000: consider a dedicated FX broker who can quote a negotiated rate. For business volumes, this can be worth thousands per year.',
        'Recurring transfers (salary, rent, tuition): set up with a remittance specialist that has good API or scheduled-transfer support.',
      ] },
      { type: 'h2', text: 'A five-minute checklist before sending' },
      { type: 'list', items: [
        'Check the mid-market rate (for example, on this site).',
        'Get a quote from your provider.',
        'Calculate the total cost: fee + (mid-market rate − offered rate) × amount.',
        'Confirm how the recipient will be paid (bank deposit, cash pickup, wallet).',
        'Double-check the recipient name, account number, and country — transfers to the wrong account can be very hard to reverse.',
      ] },
      { type: 'p', text: 'A little shopping around genuinely pays. On a $5,000 transfer, the difference between a bank wire and a competitive specialist can easily be $100–$200.' },
    ],
  },

  {
    slug: 'best-time-to-exchange-currency',
    title: 'Best Time to Exchange Currency: What the Research Actually Says',
    description: 'Timing the market is famously hard. Here is what works, what does not, and how to think about when to convert.',
    readingMinutes: 6,
    updated: '2026-04-20',
    category: 'Strategy',
    tags: ['timing', 'strategy', 'forex'],
    body: [
      { type: 'lead', text: '"Should I convert now or wait?" is one of the most common questions people ask about foreign exchange. The honest answer is: usually you cannot predict short-term movements, but you can structure conversions so timing matters less. Here is what actually works.' },
      { type: 'h2', text: 'The bad news: short-term timing is close to a coin flip' },
      { type: 'p', text: 'Currency markets are famously difficult to predict over days or weeks. Professional traders — with access to real-time data, Bloomberg terminals, and teams of analysts — still get short-term directional calls wrong about half the time. If they cannot time it, you almost certainly cannot either.' },
      { type: 'p', text: 'That does not mean movements are random. They are driven by real information — interest-rate expectations, inflation releases, political events. But that information is priced in almost instantly when it arrives, so by the time you read it in the news, the rate has already adjusted.' },
      { type: 'h2', text: 'The good news: you rarely need to time anything' },
      { type: 'p', text: 'For most people converting money, the rate will fluctuate within a 1%–3% band over any given month. For a $500 conversion, that is the difference between converting today and waiting a month: maybe $5–$15. For a $5,000 conversion, it is $50–$150. For a $50,000 conversion, it is $500–$1,500.' },
      { type: 'p', text: 'If the amount matters to you, the smart move is usually not to try to pick the perfect day but to average your conversions over time — known as "dollar-cost averaging" in the investing world.' },
      { type: 'h2', text: 'Strategy 1: Convert what you need, when you need it' },
      { type: 'p', text: 'For trips, purchases, and remittances with a fixed deadline: convert the amount you need shortly before you need it. Trying to wait for a better rate can easily backfire, and the mental overhead is usually not worth the expected savings.' },
      { type: 'h2', text: 'Strategy 2: Split large amounts across time' },
      { type: 'p', text: 'For larger amounts — buying a home abroad, paying annual tuition, funding a long trip — split the conversion into 3–6 tranches spaced over weeks or months. This gets you the average rate over that window, which is statistically a very good outcome compared to picking a single day.' },
      { type: 'h2', text: 'Strategy 3: Rate alerts and limit orders' },
      { type: 'p', text: 'If you have a specific target in mind ("I\'ll convert when USD/BRL reaches 5.20"), most remittance specialists offer rate alerts or limit orders that execute automatically at a price you set. This removes the emotional component and lets you wait passively.' },
      { type: 'callout', text: 'Set the target at a rate you would be genuinely happy with — not the best rate of the past 5 years. Aim for the top quartile of the last 6–12 months and you will usually get filled within weeks or months.' },
      { type: 'h2', text: 'What about seasonality?' },
      { type: 'p', text: 'Some currencies show mild seasonal patterns. The Swiss franc historically strengthens in times of global risk-off. Commodity-linked currencies (AUD, CAD, BRL) often move with commodity-price cycles. But these effects are small, unreliable, and mostly already priced in. Do not structure a conversion around them.' },
      { type: 'h2', text: 'What about day-of-week or time-of-day?' },
      { type: 'p', text: 'Liquidity is lowest during the Asia overnight hours, which can cause slightly wider spreads. For retail conversion services, this rarely matters — they quote the same rate 24/7 within their caching window. Ignore advice that tells you to convert "on Tuesdays at 10 AM." The effect, if any, is microscopic.' },
      { type: 'h2', text: 'The best rule of thumb' },
      { type: 'p', text: 'Pick a competitive provider. Convert when you need the money. For large amounts, split over time. Do not lose sleep over day-to-day movements — the noise is bigger than the signal for almost everyone.' },
    ],
  },

  {
    slug: 'major-world-currencies',
    title: 'A Guide to the Major World Currencies',
    description: 'USD, EUR, JPY, GBP, CHF, CAD, AUD, CNY — the eight currencies that make up most of the world\'s foreign-exchange volume.',
    readingMinutes: 8,
    updated: '2026-04-20',
    category: 'Reference',
    tags: ['currencies', 'reference', 'fx-majors'],
    body: [
      { type: 'lead', text: 'The foreign-exchange market is enormous, but most of its volume concentrates in a surprisingly small set of currencies. Eight currencies together account for the overwhelming majority of daily FX turnover. If you understand these, you understand most of what goes on in global finance.' },
      { type: 'h2', text: 'The majors' },
      { type: 'p', text: 'The "majors" are the currencies of countries with the largest, most open capital markets. Trading them against USD has the deepest liquidity and the narrowest spreads.' },

      { type: 'h3', text: 'US Dollar (USD)' },
      { type: 'p', text: 'The global reserve currency. On one side of roughly 88% of all FX trades. Issued by the Federal Reserve. Covered in depth on our dedicated USD guide.' },

      { type: 'h3', text: 'Euro (EUR)' },
      { type: 'p', text: 'The currency of 20 EU member states. Second in global reserves and FX volume. Issued by the European Central Bank. The EUR/USD pair is the single most traded instrument in the world.' },

      { type: 'h3', text: 'Japanese Yen (JPY)' },
      { type: 'p', text: 'Third by FX volume. The Bank of Japan has maintained near-zero or negative interest rates for decades, which makes JPY a popular funding currency for "carry trades" — borrowing in yen to invest in higher-yielding currencies. Famous for moving sharply when global risk appetite shifts.' },

      { type: 'h3', text: 'British Pound (GBP)' },
      { type: 'p', text: 'The oldest still-used major currency. Issued by the Bank of England. Historically strong against most currencies. More volatile since 2016 due to Brexit-related news.' },

      { type: 'h3', text: 'Swiss Franc (CHF)' },
      { type: 'p', text: 'Considered one of the ultimate "safe haven" currencies. Switzerland\'s political neutrality and large foreign reserves mean CHF tends to rise during global crises. The Swiss National Bank has intervened repeatedly to prevent excessive appreciation.' },

      { type: 'h3', text: 'Canadian Dollar (CAD)' },
      { type: 'p', text: 'Often called the "loonie" after the bird on the $1 coin. Heavily correlated with oil prices and US economic activity.' },

      { type: 'h3', text: 'Australian Dollar (AUD)' },
      { type: 'p', text: 'Correlated with commodity exports (iron ore, coal, gold) and Chinese demand. Known in FX circles as a "risk-on" currency — it tends to rise when investors are optimistic.' },

      { type: 'h3', text: 'Chinese Yuan (CNY)' },
      { type: 'p', text: 'Technically managed by the People\'s Bank of China within a trading band. Less freely floating than other majors. Its offshore variant (CNH) trades more freely in Hong Kong. CNY\'s share of global payments has been growing steadily.' },

      { type: 'h2', text: 'Notable non-majors worth knowing' },
      { type: 'list', items: [
        'Brazilian Real (BRL) — the most important Latin American currency, volatile and commodity-linked.',
        'Indian Rupee (INR) — underpins the world\'s most populous country and a major remittance destination.',
        'Mexican Peso (MXN) — the most actively traded emerging-market currency.',
        'South Korean Won (KRW) — backed by one of Asia\'s largest and most tech-driven economies.',
        'Singapore Dollar (SGD) — managed as a "basket" against major trading partners, known for stability.',
      ] },

      { type: 'h2', text: 'How this helps you' },
      { type: 'p', text: 'Most people only need to think about two or three currencies day-to-day — their home currency, the one they travel with, and maybe USD or EUR. But understanding the broader landscape helps you make sense of news, spot cross-rate opportunities, and judge when a quoted rate seems off.' },
    ],
  },
]

export function getGuide(slug) {
  return GUIDES.find((g) => g.slug === slug)
}
