// Hand-written per-pair editorial intros for indexable currency pair pages. Wave 1 = POPULAR_PAIRS plus reverses (38 keys) per D-09/D-10. Wave 2 (40 major-major crosses) deferred to Phase 1.5 per CONTEXT.md D-11 + RESEARCH.md §6.

export const PAIR_PROFILES = {
  'USD-BRL': `For Brazilian importers, exporters, and households tracking the cost of foreign-priced goods, the USD to BRL conversion is the single most consequential rate on the screen. Brazil settles most commodity exports in dollars, from soy and iron ore to beef and oil, so the real moves in tight correlation with global commodity cycles and with US Federal Reserve policy. When the Fed raises rates, capital tends to flow out of emerging markets and the real weakens. The Banco Central do Brasil sets its own Selic policy rate to defend the currency and anchor inflation expectations, often in the opposite direction. The day-to-day USD-BRL print also shapes household budgets in Brazil: streaming subscriptions, international tuition, software-as-a-service tools, and online purchases from US stores are all priced in dollars and converted at the retail rate plus the IOF tax. The mid-market figure displayed on this page is the benchmark against which any bank, fintech, or card spread should be measured before a transaction settles.`,

  'BRL-USD': `Travelers leaving Brazil for the United States, freelancers invoicing a US client in dollars, and families sending support to relatives studying abroad all begin with the same question: how many dollars does one real actually buy today? The answer is set in the global interbank market, where the Banco Central do Brasil has no direct influence beyond its policy rate and occasional spot intervention. On the US side, the Federal Reserve sets the broader interest-rate environment that the dollar trades against. Because the real is far more volatile than the dollar, the BRL-USD print moves mostly in response to Brazilian fiscal news, commodity prices, and emerging-market risk sentiment. A reader converting in this direction should pay close attention to the IOF tax on outbound conversions and to the all-in spread offered by Brazilian banks and brokerages, which can vary by more than two percentage points between the worst and best providers on the same business day.`,

  'EUR-USD': `No currency pair in the world trades more volume than EUR-USD. The European Central Bank, headquartered in Frankfurt, sets monetary policy for the twenty euro-area members, while the US Federal Reserve sets it for the dollar. The interest-rate gap between the two anchors most of the long-term direction of the pair. Day-to-day moves come from inflation prints in either bloc, payroll data out of Washington, manufacturing surveys out of Germany, and the broader risk environment. For a European company invoicing a US customer, a European tourist budgeting a trip to New York, or an American business buying components from a German supplier, the EUR-USD rate quoted here is the mid-market reference. Retail conversions through a bank or a card will run roughly one to three percent above this figure, depending on the provider. Online brokers and modern remittance services tend to be the closest to mid-market for medium-sized amounts, while airport kiosks remain the most expensive option on either side of the Atlantic.`,

  'USD-EUR': `Americans planning a trip to Paris, US-based subscribers paying for European software, and exporters in the United States invoicing customers across the European Union all need the USD-EUR direction. The Federal Reserve and the European Central Bank operate on very different policy cycles, so the two rates can diverge for long stretches before snapping back. When the dollar strengthens against the euro, every dollar buys more European goods, services, and travel; when it weakens, the opposite holds. Reader-relevant context: prices inside the euro area are quoted in euros across all twenty member states, from Ireland to Greece, so a single mid-market figure governs travel and online spending across the entire bloc. The rate shown here is the reference midpoint between the institutional bid and ask in the global interbank market. Any consumer-facing conversion will sit a fraction of a percent to several percent above it, depending on whether the conversion runs through a card network, a transfer specialist, a high-street bank, or a money-exchange counter at the airport.`,

  'GBP-USD': `Known to traders as "cable" after the transatlantic telegraph cable that once carried the quote between London and New York, GBP-USD is one of the four most actively traded currency pairs in the world. The Bank of England sets policy in Threadneedle Street, while the Federal Reserve sets policy in Washington. The pair tends to move on UK inflation prints, US payroll data, fiscal announcements from either Treasury, and the broader political backdrop in the United Kingdom. Brexit and its aftermath produced some of the largest single-day moves in cable's modern history. For a UK resident sending money to a US bank account, a British exporter pricing a contract in dollars, or an American buying a London property, the figure quoted on this page is the mid-market starting point. Retail spreads vary widely: high-street UK banks tend to run between 2 and 4 percent above mid-market on outbound transfers, while online specialists routinely deliver well under one percent for similar amounts.`,

  'USD-GBP': `Americans visiting London, US companies hiring contractors in the United Kingdom, and online shoppers buying from British retailers all reach for the USD-GBP direction. The pound is one of the oldest currencies still in continuous use, and the Bank of England has set its policy rate independently since gaining operational independence in 1997. On the other side, the Federal Reserve sets the dollar rate. The interest-rate gap between the two central banks anchors the long-term trend of the pair, while shorter moves track UK economic data, US labour-market prints, and broader risk sentiment. Practical note for a US-based reader: prices in the United Kingdom are quoted in pounds inclusive of value-added tax, so the headline figure on a shop window is closer to the all-in cost than equivalent quotes back home. The mid-market rate shown on this page is the reference midpoint; any actual conversion through a US card or bank will include a small spread on top of it.`,

  'USD-JPY': `Sitting alongside EUR-USD and GBP-USD as one of the most heavily traded pairs in the world, USD-JPY carries an outsized role in global financial markets. The Bank of Japan has run an ultra-loose monetary policy for most of the last two decades, while the Federal Reserve sets its dollar policy on a very different cycle. That gap makes the yen a popular funding currency for carry trades and gives USD-JPY one of the widest persistent interest-rate differentials in the major-currency space. For travelers heading to Japan, importers buying Japanese cars or electronics in dollars, and Japanese exporters pricing US-bound shipments, the rate matters in opposite directions. Practical context for a reader converting dollars to yen: Japan is one of the most cash-intensive major economies, and the unit value of the yen is very low, so any traveler should expect to handle larger note counts than they would in Europe. The figure displayed on this page is the global mid-market midpoint before any provider spread is added.`,

  'JPY-USD': `Japanese travelers booking US flights, Japanese companies paying for US-based cloud services, and US residents receiving payment from a Japanese employer all start from the JPY-USD direction. Because the yen has such a low unit value, this rate is usually expressed with several decimal places, and small absolute moves represent meaningful percentage changes. In Tokyo, the Bank of Japan sets the yen policy rate; on the dollar side, the Federal Reserve makes the call from Washington. Over the longer term, the gap between those two policy rates does most of the work in driving JPY-USD. Shorter moves track US inflation data, Japanese current-account surpluses, and the global risk environment, since the yen tends to appreciate as a safe haven when other markets sell off. Anyone converting at a Japanese bank or airport kiosk should compare the offered rate against the mid-market figure shown here: high-street spreads in Tokyo are typically narrower than in many Western capitals, but the difference between providers is still worth a quick check before committing to a sizeable conversion.`,

  'EUR-GBP': `Cross-channel trade between the United Kingdom and the European Union runs through EUR-GBP in volumes worth hundreds of billions a year. The European Central Bank and the Bank of England operate on different policy cycles, and the gap between them sets the broad direction of the pair over months and quarters. Shorter moves track UK inflation prints, eurozone manufacturing data, and political headlines that affect either bloc. For a UK importer buying components from Germany, an Irish exporter invoicing a London customer, or a Spanish resident receiving rent from a UK tenant on a British-bank account, the EUR-GBP rate determines the all-in cost. Mid-market reference rates such as the one shown here are the cleanest single number to use for planning. Card networks, transfer specialists, and high-street banks add their own spreads on top, which range from a fraction of a percent at the cheapest end to several percent at airport counters and traditional bank wires.`,

  'GBP-EUR': `British residents booking holidays in Spain or Italy, UK retirees living in Portugal or France on a pension paid in pounds, and London-based contractors invoicing euro-area customers all begin with the GBP-EUR direction. The Bank of England sets the sterling policy rate, while the European Central Bank sets the rate for all twenty members of the euro area. The gap between those two policy paths is the single largest force behind the long-term trend of GBP-EUR. Shorter moves come from UK inflation and growth data, eurozone surveys, and political events on either side of the Channel. A common practical question among UK readers: should a planned European holiday be funded by buying euros in advance, or by paying on card and converting at the point of sale? The mid-market rate shown here is the reference number for that decision, and the answer usually depends on the spread quoted by the specific card or provider, not on any near-term forecast of where the rate is heading.`,

  'USD-CNY': `Connecting the world\'s two largest economies, USD-CNY is one of the most politically watched currency pairs on the planet. The People\'s Bank of China manages the renminbi within a daily tolerance band against a basket of trade partners, so the pair tends to move in quieter steps than fully floating majors. On the other side of the pair, the Federal Reserve sets the dollar under a free-floating regime. For a US importer paying a Chinese factory, an American student paying tuition at a Shanghai university, or a US-based ecommerce seller sourcing inventory from a Shenzhen supplier, the USD-CNY rate is the starting point. Note that an offshore variant, CNH, trades freely in Hong Kong and sometimes diverges from the onshore CNY by a small margin. The mid-market figure shown here uses the standard CNY quote. Settlement through SWIFT bank wires or through specialist remittance corridors will add a spread on top, and US-China remittance flows are subject to additional compliance reviews that can slow down larger transfers by several business days.`,

  'CNY-USD': `Chinese tourists planning a trip to the United States, Chinese students paying US university fees, and Chinese exporters pricing a contract for a US buyer all start from the CNY-USD direction. The People\'s Bank of China sets a central parity rate each trading day and allows the currency to float within a narrow band around it, the Federal Reserve sets the dollar under a fully free-floating regime in Washington. Capital controls on outbound flows from mainland China shape how the pair behaves in practice: the offshore CNH market in Hong Kong tends to be more responsive to global sentiment than the onshore CNY market quoted here. For US-bound spending, the day-to-day rate matters less than the all-in cost of the conversion, which depends on whether the funds move through a bank wire, a UnionPay card, or a digital wallet that converts at point of sale. The mid-market reference on this page provides the cleanest baseline against which all of those options can be compared.`,

  'USD-INR': `Driven by one of the world\'s largest remittance corridors, USD-INR moves billions of dollars from US-based Indian diaspora workers back to families across the Indian subcontinent every quarter. The Reserve Bank of India sets the rupee policy rate and intervenes in the spot market to smooth volatility, while the Federal Reserve sets the dollar side. India runs a persistent current-account deficit and imports most of its crude oil in dollars, so the rate is particularly sensitive to global oil prices and to US Treasury yields. For US tech companies paying salaries to engineers in Bangalore or Hyderabad, for American students paying tuition at the Indian Institutes of Technology, and for the very large remittance corridor between the US and India, the all-in cost depends on the spread added by the chosen provider on top of the mid-market reference. Digital remittance services that specialize in this corridor routinely deliver rates within half a percent of the figure shown here, well below traditional bank wires.`,

  'INR-USD': `Indian travelers planning a trip to the United States, Indian importers paying for US-made medical equipment or software licences, and Indian companies receiving venture capital from US investors all begin from the INR-USD direction. Because of the rupee\'s small unit value, the quote on this page carries several decimal places; what looks like a small absolute movement can amount to a meaningful percentage shift. The Reserve Bank of India runs rupee policy from Mumbai; the dollar comes from the Federal Reserve. Outbound conversions from India face strict capital-control rules under the Liberalised Remittance Scheme, which caps the total amount an individual can send abroad in a single financial year. The mid-market reference shown here is the cleanest number for budgeting, but the actual rate received from a bank or authorised dealer will reflect both their spread and the documentation requirements of the underlying remittance category. Checking the all-in cost across two or three providers before a sizeable conversion is almost always worth the few minutes it takes.`,

  'USD-CAD': `Often called the "loonie" pair after the bird pictured on the Canadian dollar coin, USD-CAD is one of the most stable major pairs in the world. The Bank of Canada in Ottawa sets the Canadian policy rate; the Federal Reserve sets the US side, and the two central banks tend to move in roughly similar directions because the two economies are deeply integrated. Crude oil prices play an outsized role in the rate: Canada is one of the largest oil exporters to the United States, and the loonie strengthens when oil prices rise. For Americans travelling to Canada, US companies paying contractors in Toronto or Vancouver, and US ecommerce shoppers buying from Canadian retailers, the all-in cost of a conversion comes down to the spread their bank or card adds on top of the mid-market reference. Cross-border traffic between the two countries is heavy enough that many border-town businesses accept either currency directly, though usually at a discount to the spot rate displayed here.`,

  'CAD-USD': `Canadian travelers crossing the border into the United States, Canadian companies invoicing US customers in dollars, and Canadian residents shopping on US-based websites all start from the CAD-USD direction. The Bank of Canada owns Canadian policy from Ottawa, the Federal Reserve owns US policy from Washington; because the two economies are deeply linked through trade, energy flows, and labour mobility, the long-term trend of CAD-USD is usually mild compared with other major pairs. Crude oil prices, US payroll data, and Canadian inflation prints do most of the short-term work. Practical note for Canadian readers: many US retailers and hotels accept Canadian credit cards directly, but the conversion is performed at the card network rate plus a foreign-transaction fee that typically runs around 2.5 percent. The mid-market reference rate shown on this page is the cleanest starting point for comparing that cost against alternatives such as a multi-currency account, a US-dollar pre-paid card, or a direct bank wire for larger amounts.`,

  'USD-CHF': `Regarded by many traders as the cleanest expression of a flight-to-safety move, USD-CHF moves sharply when global risk appetite falls and investors crowd into Swiss francs. The Swiss National Bank in Zürich sets the franc policy rate and has a long history of active intervention to manage the currency, including the famous removal of the EUR-CHF floor in January 2015 that produced one of the largest single-day moves in modern FX history. The Federal Reserve sets the dollar side under a much more conventional framework. For American travelers heading to Zürich, Geneva, or Bern, US companies hiring Swiss-based contractors, and US wealth managers settling accounts with Swiss banks, the mid-market value listed on this page provides the starting reference for any conversion. Day-to-day costs in Switzerland sit among the highest in the world, so even a small spread on top of the spot rate can add up across a week of meals, hotels, and transport. Running a quick three-way comparison before settling a sizeable transfer is almost always worth the time.`,

  'CHF-USD': `Swiss residents planning a US trip, Swiss companies invoicing American customers, and Swiss-based asset managers settling positions in US securities all begin with the CHF-USD direction. The Swiss National Bank, based in Bern and Zürich, controls franc policy; on the US side, the Federal Reserve controls the dollar. The franc tends to appreciate during periods of global stress because of Switzerland\'s political neutrality, strong property rights, and deep banking system. That safe-haven behaviour means CHF-USD can move several percent in a short window when risk sentiment shifts. For a Swiss reader converting to dollars, the practical cost depends less on day-to-day timing than on the spread added by the chosen provider. Swiss high-street banks tend to offer broadly competitive rates to retail customers because of strong domestic competition, but specialist online platforms can still deliver tighter spreads on larger amounts. The mid-market rate displayed here works as the cleanest yardstick available for evaluating any quoted offer.`,

  'USD-AUD': `Sitting on one of the most actively traded commodity-currency pairs in the world, USD-AUD reflects two very different economies linked by deep trade and investment flows. The Reserve Bank of Australia runs Aussie policy from Sydney, opposite the Federal Reserve on the US side. The Australian dollar is heavily correlated with iron ore, coal, and LNG prices, and with the growth pulse of China, which buys most of Australia\'s mining exports. When global risk sentiment is strong, the Aussie tends to rise against the US dollar; in risk-off periods it usually falls. For Americans planning a trip to Sydney or Melbourne, US companies paying Australian-based contractors, and US ecommerce shoppers buying from Australian retailers, the mid-market figure on this page provides the starting reference. Card networks and bank wires typically add a spread of between 1 and 3 percent on top, while specialist remittance services often deliver well under one percent for larger amounts on the US-Australia corridor.`,

  'AUD-USD': `Australian travelers heading to the United States, Australian companies invoicing US customers in dollars, and Australian residents shopping on American websites all start from the AUD-USD direction. The Reserve Bank of Australia and the Federal Reserve each set their own policy rate; the long-term gap between the two does much of the work in shaping AUD-USD. Shorter moves come from US payroll data, Australian inflation prints, commodity prices, and shifts in global risk sentiment. Practical context for Australian readers: many US-facing services charge in dollars regardless of where the customer is based, so subscription costs, software licences, and cloud-hosting bills are converted through the chosen card network at its own spread. The mid-market figure on this page anchors the cleanest baseline for measuring each of those conversions. For larger amounts such as property deposits, vehicle imports, or university tuition, a direct bank wire or specialist remittance provider often delivers a better all-in rate than a credit card.`,

  'EUR-BRL': `Particularly relevant for the large European tourist flow into Brazil and for Brazilian importers buying European industrial goods, EUR-BRL is one of the most actively traded euro-real pairs after the dollar-real benchmark. From Frankfurt, the European Central Bank sets the euro policy rate for all twenty euro-area members; in Brasília, the Banco Central do Brasil owns the Selic rate that anchors the real. The pair is volatile by major-currency standards, mainly because the real is far more sensitive than the euro to commodity cycles and to emerging-market risk sentiment. For a Brazilian household funding a relative\'s European studies, a Brazilian importer paying a German machinery supplier, or a Portuguese investor settling a property purchase in São Paulo, the mid-market figure on this page sets the cleanest benchmark. Brazilian banks and brokerages charge a spread on top, plus the IOF tax on outbound conversions. Quickly comparing two or three providers before settling can shift the all-in cost by more than a full percentage point.`,

  'BRL-EUR': `Residents of Brazil planning European holidays, local companies paying for European software licences, and students travelling to study in Lisbon, Madrid, or Berlin all begin with the BRL-EUR direction. The Banco Central do Brasil sets the real policy rate, while the European Central Bank sets the euro side. Because the real is more volatile than the euro, the long-term direction of BRL-EUR is dominated by Brazilian factors: fiscal policy, commodity exports, and the Selic rate path. Practical context for Brazilian readers: outbound conversions from Brazil are subject to the IOF tax, which varies by remittance category and can add a meaningful cost on top of the bank or fintech spread. Cards used abroad also trigger IOF on each transaction. The mid-market figure on this page provides the cleanest yardstick for evaluating any quoted offer, whether it comes from a traditional Brazilian bank, a brokerage, or a newer fintech that specializes in international transfers.`,

  'GBP-BRL': `Helping connect the Brazilian diaspora in the United Kingdom with families back home, GBP-BRL is one of the most actively used non-dollar remittance corridors for Brazil. Sterling policy is run by the Bank of England from Threadneedle Street; the Selic rate that anchors the real is run by the Banco Central do Brasil. The gap between those two rates does much of the work in shaping the long-term trend, while shorter moves track UK inflation prints, Brazilian fiscal news, and commodity prices. For a UK-based Brazilian sending support to relatives in São Paulo, a British importer buying Brazilian coffee or beef, or a UK pensioner funding a stay on Brazil\'s northeast coast, the mid-market figure shown here is the starting point. Specialist remittance services on this corridor have proliferated in the last decade and now routinely offer all-in costs under one percent for medium-sized amounts. Traditional bank wires from UK high-street banks tend to run several percentage points above mid-market once both their spread and their flat fee are factored in.`,

  'BRL-GBP': `Travelers booking trips to London or Edinburgh, importers in Brazil paying for British equipment, and families supporting a relative studying at a UK university all start from the BRL-GBP direction. The Selic rate, Brazil\'s policy anchor, is run by the Banco Central do Brasil; sterling policy is run by the Bank of England. As with all BRL crosses, the real does most of the moving: it is significantly more volatile than the pound, and its direction is driven by Brazilian fiscal policy, the Selic rate, and global commodity cycles. A UK-bound conversion from a Brazilian account incurs IOF on top of whatever spread the bank or fintech of choice applies. Online specialist remittance services tend to deliver the tightest all-in spreads on this corridor, while airport exchange counters in either country remain the most expensive option by a wide margin. The mid-market reference rate displayed here is the cleanest baseline against which any quoted offer should be checked before a sizeable conversion settles.`,

  'JPY-BRL': `Reflecting the deep ties between the Japanese-Brazilian community and the Japanese diaspora in São Paulo, JPY-BRL is one of the most culturally significant cross-rates for Brazil despite its modest traded volume. Yen policy is set by the Bank of Japan in Tokyo; the Banco Central do Brasil runs Brazil\'s Selic rate from Brasília. Because the yen has such a low unit value, the rate is usually quoted with several decimal places. The yen behaves as a safe haven and tends to strengthen during global risk-off episodes, while the real tends to weaken in the same environment, so the two currencies often move in opposite directions during financial stress. For a Japanese importer of Brazilian coffee or iron ore, a Japanese-Brazilian family sending remittances between Tokyo and São Paulo, or a Japanese tourist visiting Brazil, the mid-market rate displayed on this page provides the cleanest starting figure. Comparing the IOF tax, bank spread, and remittance fees across two or three providers is almost always worthwhile.`,

  'BRL-JPY': `Households planning a trip to Tokyo, companies paying for Japanese industrial machinery, and descendants of Japanese immigrants in São Paulo sending support to relatives back in Japan all begin with the BRL-JPY direction. Brazil\'s policy anchor, the Selic rate, sits with the Banco Central do Brasil; yen policy sits with the Bank of Japan. The real is far more volatile than the yen, so most of the day-to-day movement reflects fiscal headlines from Brasília, agricultural and metal commodity prints, and shifts in global emerging-market risk appetite. A Japan-bound transfer out of a Brazilian account triggers the IOF tax on top of the provider\'s own spread. Because of the yen\'s tiny unit value, this page displays the rate with several decimal places, and modest absolute moves can amount to meaningful percentage shifts. The figure here sits at the midpoint of the global interbank quote, and it serves as the cleanest baseline for evaluating any retail quote on the corridor.`,

  'CAD-BRL': `Increasingly relevant for the growing Brazilian community in Toronto, Vancouver, and Montréal, CAD-BRL is one of the steadier BRL crosses among the majors. In Ottawa, the Bank of Canada owns the Canadian policy rate; the Selic rate that anchors the real comes from the Banco Central do Brasil in Brasília. Both economies are heavily commodity-linked, so the two currencies sometimes move in similar directions when global commodity prices shift, though the real is much more volatile in either direction. For a Brazilian working in Canada and sending support to family back home, a Canadian importer of Brazilian iron ore or beef, or a Canadian pensioner funding a stay on Brazil\'s coast, the mid-market figure on this page sets the reference midpoint. Specialist remittance corridors between Canada and Brazil have improved markedly in recent years, with several online providers offering all-in costs well under one percent for medium amounts. Traditional bank wires tend to run noticeably above mid-market once both the spread and the wire fee are factored in.`,

  'BRL-CAD': `Holidaymakers from Brazil planning a trip to Canada, agribusiness firms buying Canadian fertiliser or farm machinery, and students travelling to study in Toronto or Vancouver all start from the BRL-CAD direction. Brazil\'s real moves with the Selic rate, set in Brasília by the Banco Central do Brasil; Canadian policy is owned by the Bank of Canada. In this cross, as in all BRL pairs, the real does most of the moving: it is more volatile than the loonie and reacts more sharply to commodity-price shifts and to Brazilian fiscal news. A Canada-bound conversion from a Brazilian account adds the IOF tax on top of the bank or fintech spread; card transactions in Canada also incur IOF on every swipe, so for longer stays a pre-funded Canadian-dollar account or pre-paid card often delivers a lower all-in cost. The mid-market reference displayed here is the cleanest baseline against which any retail quote can be benchmarked before a sizeable conversion goes through.`,

  'AUD-BRL': `Australian visitors to Brazil, Australian importers of Brazilian commodities, and the Australian wing of the Brazilian football and music community all rely on AUD-BRL for cross-currency conversions. Aussie policy is owned by the Reserve Bank of Australia, headquartered in Sydney; the Selic rate that drives the real is owned by the Banco Central do Brasil. Both currencies are commodity-linked: the Aussie tracks iron ore, coal, and LNG prices, while the real tracks soy, iron ore, beef, and oil. Despite that surface similarity, the two move quite differently in practice because the real is far more sensitive to political and fiscal news in Brasília. For an Australian importer settling an invoice with a São Paulo supplier, an Australian tourist budgeting a Brazil trip, or a Brazilian based in Sydney sending support home, the mid-market reference on this page acts as the starting figure. Online specialist remittance services usually deliver tighter spreads than traditional bank wires, and running a quick three-way comparison before a large transfer is almost always worth a few minutes.`,

  'BRL-AUD': `Visitors from Brazil planning trips to Sydney or Melbourne, mining firms paying Australian suppliers for equipment, and families sending support to relatives studying at Australian universities all begin with the BRL-AUD direction. The Selic rate, which anchors the Brazilian real, is run from Brasília by the Banco Central do Brasil; Australian policy is owned by the Reserve Bank of Australia. The real is more volatile than the Aussie, so most of the rate movement comes from Brazilian factors: fiscal news, the Selic rate, and global emerging-market sentiment. An Australia-bound transfer out of a Brazilian account triggers IOF on top of whatever spread the chosen provider applies. Australia is geographically distant and time-zoned away from Brazil, so settlement on large transfers often takes an extra business day compared with European or North American corridors. The figure on this page anchors the reference midpoint, and serves as the cleanest available number against which retail quotes should be measured before settling.`,

  'CHF-BRL': `Linking one of the world\'s safest-haven currencies with one of the most volatile major emerging-market currencies, CHF-BRL is a textbook example of a risk-on, risk-off pair. The franc is governed by the Swiss National Bank; Brazil\'s Selic rate, the anchor for the real, is set by the Banco Central do Brasil in Brasília. The two currencies often move in opposite directions during global stress: the franc tends to appreciate as money flows into safe havens, while the real tends to weaken as capital leaves emerging markets. For a Swiss importer of Brazilian commodities, a Brazilian household sending tuition support to a child studying in Zürich or Lausanne, or a Swiss-based asset manager with Brazilian holdings, the mid-market figure shown on this page is the reference point. Specialist remittance services on this corridor are less common than on the dollar or euro routes, but for larger amounts a direct bank wire from a major Swiss bank typically delivers a competitive all-in rate compared with traditional Brazilian outbound options.`,

  'BRL-CHF': `Tourists from São Paulo planning trips to Zürich or Geneva, pharmaceutical importers buying Swiss precision instruments, and families supporting a student at a Swiss university all start from the BRL-CHF direction. In Brasília, the Banco Central do Brasil sets the Selic rate that drives the real; the Swiss National Bank owns franc policy. Day-to-day costs in Switzerland are among the highest in the world, which makes the IOF tax and the bank spread on outbound conversions from Brazil particularly costly in absolute terms. The mid-market reference rate shown here is the cleanest yardstick for evaluating any quoted offer from a Brazilian bank, brokerage, or fintech. For longer stays in Switzerland, a multi-currency account or a pre-funded franc card often delivers a lower all-in cost than swiping a Brazilian credit card at the point of sale, since each card transaction abroad triggers a fresh IOF charge on top of the network spread.`,

  'CNY-BRL': `Vital to one of the most economically consequential bilateral relationships in the southern hemisphere, CNY-BRL channels the trade flow between China and its largest South American partner. China is the single biggest buyer of Brazilian soy, iron ore, and beef, and the relationship has reshaped Brazilian export patterns over the last two decades. From Beijing, the People\'s Bank of China steers the renminbi inside a daily tolerance band; the Banco Central do Brasil controls the Selic rate that anchors the real. Capital controls on the Chinese side mean retail conversions in this direction often pass through dollar intermediation rather than direct CNY-BRL settlement. For Chinese importers buying Brazilian commodities, Chinese tourists visiting Brazil, and Brazilian-Chinese families sending remittances, the figure on this page provides the reference midpoint. Comparing the all-in cost across a direct corridor and a dollar-intermediated route is worthwhile, since the spread on the latter sometimes ends up tighter despite involving two conversions instead of one.`,

  'BRL-CNY': `Importers buying Chinese-made electronics, machinery, and components, exporters of agricultural commodities receiving payment in renminbi, and residents of Brazil planning trips to Shanghai or Beijing all begin with the BRL-CNY direction. From Brasília, the Banco Central do Brasil oversees the Selic rate that governs the real; from Beijing, the People\'s Bank of China keeps the renminbi inside a managed corridor against a basket of trade partners. Direct BRL-CNY conversions are less common at the retail level than dollar-intermediated routes, because the Chinese capital account is not fully open. A renminbi-bound transfer from Brazil incurs the IOF tax on top of whatever spread the chosen bank or fintech applies. The figure here represents the global interbank midpoint for the direct pair, and it provides the cleanest available baseline against which any retail quote from a Brazilian bank, brokerage, or fintech can be compared before a sizeable conversion settles into the destination account.`,

  'USD-MXN': `Anchoring the most actively traded emerging-market currency pair in the world, USD-MXN moves enormous volumes every trading day. Mexico\'s deep trade relationship with the United States, its fully convertible currency regime, and the heavy cross-border manufacturing footprint along the frontier make the peso unusually liquid for an emerging-market currency. The Banco de México controls peso policy from Mexico City, opposite the Federal Reserve on the dollar. The peso tends to strengthen when US growth is strong and weaken when cross-border political tension or trade-policy noise rises. For Americans crossing into Mexico for tourism or property purchases, US companies operating maquiladora facilities, and US residents sending remittances to family in Mexico, the mid-market figure on this page sets the starting reference. The US-Mexico remittance corridor is one of the largest in the world, and specialist providers routinely keep total costs under one percent for medium amounts, well below the spreads charged by traditional bank wires.`,

  'MXN-USD': `Mexican residents crossing into the United States for shopping, work, or family visits, Mexican companies invoicing US customers, and Mexican workers in the United States holding peso-denominated savings at home all start from the MXN-USD direction. The Banco de México in Mexico City sets the peso policy rate; the Federal Reserve sets the dollar. Because Mexico runs a large trade surplus with the United States and a heavy manufacturing relationship through cross-border supply chains, the rate is unusually liquid for an emerging-market pair and the spread between bid and ask is typically tight. In US border towns, prices are often quoted in both pesos and dollars, with local shops accepting either, though usually at a discount to the mid-market rate. The reference figure shown on this page provides the cleanest baseline against which any retail quote should be benchmarked, whether the conversion runs through a Mexican bank, a US-side casa de cambio, or a specialist online provider.`,

  'USD-KRW': `Reflecting one of the deepest trade relationships in the Asia-Pacific, USD-KRW connects the United States with one of the world\'s largest manufacturing economies. The Bank of Korea sets the won policy rate from Seoul, while the Federal Reserve sets the dollar side. The won is sensitive to global semiconductor cycles, given how much of South Korea\'s export volume comes from chips, displays, and advanced electronics. The rate is also responsive to North Korean geopolitical news and to broader Asia-Pacific risk sentiment. For American visitors to Seoul, US tech companies licensing Korean intellectual property, and US-based importers buying Korean automobiles or appliances, the mid-market value listed on this page is the cleanest starting figure. Because the won has a low unit value relative to the dollar, the rate is usually quoted with several decimal places. Card networks and bank wires add a spread on top, with specialist remittance services typically delivering tighter all-in rates than high-street banks for medium-sized amounts on the US-Korea corridor.`,

  'KRW-USD': `South Korean tourists visiting the United States, Korean conglomerates settling US-dollar invoices for raw materials or aircraft, and Korean students paying tuition at US universities all begin with the KRW-USD direction. The Bank of Korea, headquartered in Seoul, runs won policy; the Federal Reserve runs dollar policy from Washington. Because the won has a low unit value, the rate is displayed with several decimal places; modest-looking shifts in the trailing digits often translate into noticeable percentage moves. South Korea runs a persistent current-account surplus and is a major exporter of semiconductors, automobiles, and advanced electronics, so the won often strengthens when global tech-cycle indicators improve and weakens when they deteriorate. For Korean readers converting to dollars, the practical cost depends mainly on the spread added by the chosen bank or specialist provider. The mid-market reference rate on this page provides the cleanest available baseline for evaluating any quoted offer before settling a sizeable conversion.`,
}

export function getPairIntro(fromCode, toCode) {
  return PAIR_PROFILES[`${String(fromCode).toUpperCase()}-${String(toCode).toUpperCase()}`] ?? null
}
